-- 插入测试项目数据
INSERT INTO requirements (
    user_id, 
    user_type, 
    user_type_other, 
    project_type, 
    project_type_other, 
    need_online, 
    traffic, 
    urgency, 
    delivery_period, 
    ui_style, 
    status, 
    budget_calculated, 
    step_data, 
    flow_node_status, 
    current_flow_node, 
    created_at, 
    updated_at
) VALUES (
    1, 
    'COMPANY', 
    NULL, 
    'WECHAT_MINIPROGRAM', 
    NULL, 
    true, 
    '{"total_users": 1000, "dau": 500, "concurrent": 100}', 
    'NORMAL', 
    7, 
    'modern', 
    'PROCESSING', 
    '{"total": 8000}', 
    '{"step1": {"selectedType": "company"}, "step2": {"selectedType": "wechat"}}', 
    '[
        {"title": "明确需求", "desc": "客户提交初步需求", "status": "completed"},
        {"title": "AI明确需求", "desc": "AI分析并完善需求", "status": "active"},
        {"title": "客户验收", "desc": "确认需求文档", "status": "pending"},
        {"title": "AI拆分任务", "desc": "自动拆分子任务", "status": "pending"},
        {"title": "AI开发", "desc": "智能编码实现", "status": "pending"},
        {"title": "AI自测", "desc": "自动化测试", "status": "pending"},
        {"title": "客户验收", "desc": "功能验收测试", "status": "pending"},
        {"title": "打包交付", "desc": "项目交付", "status": "pending"},
        {"title": "客户验收", "desc": "最终验收", "status": "pending"},
        {"title": "项目完成", "desc": "项目结束", "status": "pending"}
    ]', 
    2, 
    NOW(), 
    NOW()
) RETURNING id;
